for model_id in DiscreteSBM_VPSDE_MHD_BPROJ_N_1000_bottleneck_32 DiscreteSBM_VPSDE_MHD_BPROJ_N_1000_bottleneck_16 DiscreteSBM_VPSDE_MHD_BPROJ_N_1000_bottleneck_8 DiscreteSBM_VPSDE_MHD_BPROJ_N_4000_bottleneck_32 DiscreteSBM_VPSDE_MHD_BPROJ_N_4000_bottleneck_16 DiscreteSBM_VPSDE_MHD_BPROJ_N_4000_bottleneck_8 DiscreteSBM_VPSDE_MHD_BPROJ_N_8000_bottleneck_32 DiscreteSBM_VPSDE_MHD_BPROJ_N_8000_bottleneck_16 DiscreteSBM_VPSDE_MHD_BPROJ_N_8000_bottleneck_8 DiscreteSBM_SigmaVPSDE_MHD_BPROJ_N_1000_bottleneck_32 DiscreteSBM_SigmaVPSDE_MHD_BPROJ_N_1000_bottleneck_16 DiscreteSBM_SigmaVPSDE_MHD_BPROJ_N_1000_bottleneck_8 DiscreteSBM_SigmaVPSDE_MHD_BPROJ_N_4000_bottleneck_32 DiscreteSBM_SigmaVPSDE_MHD_BPROJ_N_4000_bottleneck_16 DiscreteSBM_SigmaVPSDE_MHD_BPROJ_N_4000_bottleneck_8 DiscreteSBM_SigmaVPSDE_MHD_BPROJ_N_8000_bottleneck_32 DiscreteSBM_SigmaVPSDE_MHD_BPROJ_N_8000_bottleneck_16 DiscreteSBM_SigmaVPSDE_MHD_BPROJ_N_8000_bottleneck_8 ;do 
sbatch <<EOF
#!/bin/bash
#SBATCH -J ${model_id}
#SBATCH --gpus=1
#SBATCH --cpus-per-gpu=16
#SBATCH --time=24:00:00
#SBATCH --partition=gpu
#SBATCH -o log/${model_id}.log
source ~/.bashrc
source /mnt/home/dheurtel/venv/genv_DL/bin/activate
python train.py --model_id ${model_id} --ckpt_folder /mnt/home/dheurtel/AstroDDPM/config/exp1 --all_models
EOF
    echo "Submitted ${model_id}"
done